spring:
  threads:
    virtual:
      enabled: true
  datasource:
    platform: postgres
    continue-on-error: false
    url: jdbc:postgresql://host.docker.internal:5432/petrol_price
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
server:
  port: 9000
bpp:
  update_time: 0 0 11 * * ?
neste:
  lv_price_link: http://www.neste.lv/lv/content/degvielas-cenas
circleK:
  lv_price_link: https://www.circlek.lv/priv%C4%81tperson%C4%81m/degvielas-cenas
  lt_price_link: https://www.circlek.lt/privatiems/degalu-kainos
  se_price_link: https://www.circlek.se/drivmedel/drivmedelspriser
gotikaAuto:
  lv_price_link: https://www.gotikaauto.lv/
viada:
  lv_price_link: http://www.viada.lv/zemakas-degvielas-cenas/
virsi:
  lv_price_link: https://www.virsi.lv/lv/privatpersonam/degviela/degvielas-un-elektrouzlades-cenas

exchange:
  link: http://192.168.0.55:10000/currency/ecb/convert/currency?currency=
