spring:
  datasource:
    platform: postgres
    continue-on-error: false
    url: jdbc:postgresql://localhost:5436/petrol_price
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
bpp:
  cron: 0 0 10 * * ?
neste:
  lv_price_link: http://www.neste.lv/lv/content/degvielas-cenas
circleK:
  lv_price_link: https://www.circlek.lv/priv%C4%81tperson%C4%81m/degvielas-cenas
gotikaAuto:
  lv_price_link: https://www.gotikaauto.lv/
viada:
  lv_price_link: http://www.viada.lv/zemakas-degvielas-cenas/
virsi:
  lv_price_link: https://www.virsi.lv/lv/degvielas-cena

