version: "3"
services:

  bpp-postgres:
    image: postgres:14-alpine
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "petrol_price"
